apiVersion: skaffold/v2alpha4
kind: Config
metadata:
  name: skaffold-frontend
build:
  artifacts:
  - image: frontend
    context: frontend
    docker:
      dockerfile: ./Dockerfile
deploy:
  statusCheckDeadlineSeconds: 540
  kubectl:
    manifests:
    - deployment-frontend.yaml
    - service-frontend.yaml